### PR TITLE
Ruby 3.0

### PR DESCRIPTION
**Pull request by dsander**
With ruby 3.0 `rexml` is not installed by default. [It was moved to a
gem][1]. Adding the gem as a dependency fixed the specs on ruby 3.0.

[1]: https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/

### CODE REVIEW

**Comment by ashkulz** [comment]
Looks like the [Ruby 3.0 build is broken with Travis CI](https://travis-ci.org/github/prontolabs/pronto/jobs/756463239). I guess we should migrate to GitHub Actions? :thinking:

**Comment by dsander** [comment]
> Looks like the [Ruby 3.0 build is broken with Travis CI](https://travis-ci.org/github/prontolabs/pronto/jobs/756463239). I guess we should migrate to GitHub Actions? 🤔

Yeah this might be a good idea, I don't know if the Ruby 3.0 build can be fixed on Travis. Even if it does the build (queue) times are ridiculous at the moment.

**Comment by dsander** [comment]
Got it working on TravisCI and submitted a draft PR which runs CI on GitHub actions: https://github.com/prontolabs/pronto/pull/397

**Review by ashkulz — APPROVED** [review]

**Comment by ashkulz** [comment]
Thanks for the contribution, @dsander!

**Pull request merged**
