### PR TITLE
Update gem version to 0.11.0

### PR DESCRIPTION
**Pull request by RGBD**
Solves #376. @mknapik you've been pretty active recently in merging pull requests.
Maybe you know what else needs to be done before new gem version release?

### CODE REVIEW

**Comment by RGBD** [comment]
Seems like I'll also have to update pronto-rubocop version to make it work, or update to 0.10.1 but I don't know if master contains breaking changes at the moment.
@mmozuras, @doomspork, @aergonaut , who can I discuss that with?

**Comment by doomspork** [comment]
Howdy @RGBD I am going to start working through these releases this week. Thanks for helping with this. :+1:

**Comment by RGBD** [comment]
Th
@doomspork , does it mean we should update to 0.10.1 instead, so that pronto-rubocop is still compatible with it?

**Comment by ashkulz** [comment]
Would appreciate if you update `CHANGELOG.md` here itself, @RGBD 🙂

I think we've had enough new features [since 0.10.0](https://github.com/prontolabs/pronto/compare/v0.10.0...master) to call it 0.11.0 -- we can always make a new release for `pronto-rubocop`, but I'm not sure if @doomspork has access to release that gem?

**Comment by RGBD** [comment]
@ashkulz, alas I don't watch this repo history closely enough to know about all the features, so I've mentioned only the one imortant for me (GitLab MR reviews).
Should I add to changelog every major merge request that happened since last mentioned in the changelog currently (feature #331, bug fix #329)?

**Comment by ashkulz** [comment]
Sorry for the long delay, but I think yes, that'd be great. I'm still not sure who has access to releasing gems, though.

**Comment by RGBD** [comment]
Done, @ashkulz.
What's the next step?
Should I also bump [pronto-rubocop](https://github.com/prontolabs/pronto-rubocop) version?

**Review by ashkulz — APPROVED** [review]

**Comment by ashkulz** [comment]
@doomspork?

**Comment by smridge** [comment]
To get `master` to work I had to run `brew install cmake pkg-config` for the `rugged` dependency. Perhaps this would be good to mention in the `README`. Happy to make a PR if this is needed and was not a one off.

**Comment by ashkulz** [comment]
@smridge I _think_ that's been a requirement for quite a while, even [0.10.0 depended on rugged](https://github.com/prontolabs/pronto/blob/v0.10.0/pronto.gemspec#L47).

**Comment by smridge** [comment]
> @smridge I _think_ that's been a requirement for quite a while, even [0.10.0 depended on rugged](https://github.com/prontolabs/pronto/blob/v0.10.0/pronto.gemspec#L47).

Ahh ok. Tried it out on a new repo, so that makes sense why I’m seeing all the fun.

**Comment by RGBD** [comment]
@doomspork, is there any approximate date when this could be reviewed/merged?

**Comment by ashkulz** [comment]
I've been granted permissions to publish to RubyGems by @doomspork, so I'll try working towards a release by the weekend (unless he has any feedback, of course :slightly_smiling_face:).

**Comment by doomspork** [comment]
Howdy @RGBD and @ashkulz :wave: My apologizes, this was lost in my ever growing notification list :cold_sweat: 

I think 0.11 seems like a sufficient bump. I don't see any reason to consider this a major or patch.

**Comment by doomspork** [comment]
Something to add to this (given this particular PR), I think we should investigate some of the semantic versioning tools that will handle publishing gems for us as features as added. The biggest change we'll need to make is ensuring PRs update the version accordingly (when necessary) and the changelog.

Automating the release of these packages would greatly reduce the maintenance burden across so many different projects

**Comment by ashkulz** [comment]
Thanks for the contribution, @RGBD! I went through the git log and added a few other PRs to the changelog, but added you as a co-author in the above commit 🙂

**Pull request closed without merging**
