### PR TITLE
GitLab MR formatter

### PR DESCRIPTION
**Pull request by dsander**
This is based on the work of @Strnadj in #308.

Since he started GitLab added [pipelines for merge requests](https://docs.gitlab.com/ce/ci/merge_request_pipelines/) which removes the need to guess the merge request for the current branch/commit. In addition to that it also re-runs jobs when the merge request target branch is changed.

### CODE REVIEW

**Comment by carlallen** [comment]
I don't like this choice as it requires gitlab premium. It's nice that the version in my pull request #349 functions out of the box with gitlab core/starter

**Comment by dsander** [comment]
It doesn't require any premium feature, we are running this branch on the pure open source CE of GitLab.

I have not seen your PR before, if I did I wouldn't have opened this one :/

I removed the branch guessing because I thought a smaller change would be easier for the maintainers, but I am obviously also happy with our changes (even though adding `CI_MERGE_REQUEST_IID` in `env_pull_id` would be nice for not having to configure anything).

**Comment by carlallen** [comment]
I could have sworn pipleines for merge requests was a preimum feature, guess I was wrong...

**Comment by fneves** [comment]
Hey all. Any news about the state of this PR?

**Comment by carlallen** [comment]
I can close #349, then I would assume this is ready for merge

**Comment by VipulSarin** [comment]
Just tested this and it works pretty well. Can the maintainers merge this and release a new gem version?

**Comment by carlallen** [comment]
Any updates on when this might get merged?

**Comment by doomspork** [comment]
Sorry for the delay all. I'm the primary maintainer these days it seems and I'm currently recovering from a pretty serious back injury that is limiting my time.

**Pull request merged**
