### PR TITLE
Updating thor dependency version

### PR DESCRIPTION
**Pull request by jer0m**
Upgrade thor dependency to v 1.0 minimum to fit Rails 6.1 needs.

### CODE REVIEW

**Comment by ashkulz** [comment]
Can you explain why you need to bump the minimum version up? Maybe you just need to include thor in the `bundle update` command.

**Comment by jer0m** [comment]
Well, apart the Rails 6.1 upgrade, I believe it's a good idea to keep dependencies up-to-date.

**Comment by ashkulz** [comment]
For a tool like pronto, supporting the lowest version possible is better as then there won't be any conflicts preventing its usage in projects. The dependency is also `>=`, so it's unlikely to be the cause of a conflict (as compared to `~>`).

**Comment by ashkulz** [comment]
Okay, so I visited the linked issue -- #370 already did what you want, so I'm closing this.

**Comment by jer0m** [comment]
Ok didn't see the other PR, I understand for the dependency matching. Thanks

**Pull request closed without merging**
