### PR TITLE
Update links referencing "mmozuras" to "prontolabs"

### PR DESCRIPTION
**Pull request by aergonaut**
`mmozuras` -> `prontolabs`

- [x] Travis CI badge
- [ ] Code coverage badge (needs project in Code Climate)
- [ ] Code Climate badge (needs project in Code Climate)
- [ ] Gemnasium badge (needs project in Gemnasium)
- [ ] Inch CI badge (needs project in Inch CI)
- [x] URLs in README

### CODE REVIEW

**Comment by ivanovaleksey** [comment]
I have thought about it too. 
Specs also contain the outdated links.

**Comment by mmozuras** [comment]
Gemnasium - done (for all prontolabs projects).

**Comment by mmozuras** [comment]
Inch CI project - done.

**Comment by mmozuras** [comment]
Code Climate project - done.

**Pull request merged**
