### PR TITLE
Adds pronto-tslint_npm to list of runners in README.md

### PR DESCRIPTION
**Pull request by eprislac**
Adds pronto-tslint_npm to the list of runners in README.md

### CODE REVIEW

**Comment by ivanovaleksey** [comment]
@eprislac now your commit has very strange name.
Why did you create a new branch?
You could just squash commits and force push to the old branch.

**Comment by eprislac** [comment]
@ivanovaleksey I'm unaware of SOP here, but force-pushing to branches that have already been published is usually considered a bad practice, so didn't think to do so. Also, I've no experience squashing commits outside of merging (The weird commit message is actually the default message you get when performing a squash-merge in git). I've amended the commit message and pushed it back up, is this satisfactory for listing my gem?

**Comment by ivanovaleksey** [comment]
I believe force pushing to your own small-fix-branch is totally fine because no one didn't fork from this branch.
I am not a judge here, but now it looks better IMO.

P. S.
You can squash commits with [interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History).

**Comment by eprislac** [comment]
Thanks for the link on interactive-rebase. On the job, I'm used to working on projects where we handle merges and PRs very differently, (we work from branches rather than forks, and most history is preserved, no matter how trivial), so appreciate the guidance on how you guys do things here. If you're doing a PR, it's your job to judge, so I'm not offended. Thanks for the link.

**Comment by mmozuras** [comment]
@eprislac thanks for the contribution and writing a runner! 🙇 

@ivanovaleksey thanks for reviewing this PR! 😄

**Pull request merged**
