### PR TITLE
Blame returning nil when file does not exist in the git tree

### PR DESCRIPTION
**Pull request by pettomartino**
Related to https://github.com/prontolabs/pronto/issues/240

Instantiating `Rugged::Blame` with a new file(`Rugged::Repository#status == index_new`) will throw `Rugged::TreeError` with `does not exist in the given tree`.

### CODE REVIEW

**Comment by doomspork** [comment]
@pettomartino what is your twitter handle?  😀

**Comment by pettomartino** [comment]
@doomspork same, @pettomartino

**Comment by durnin** [comment]
Hello, is this getting merged anytime soon? I'm also trying to use pronto with pre-commit hook using --staged. Thanks!

**Comment by doomspork** [comment]
@mmozuras any thoughts on this one, is it good to go?

**Comment by bjornlinder** [comment]
I tested out the changes in my pre-commit hook, didn't see the output I was expecting from pronto. Ideally we'd have pronto linting the newly added (staged) files. Here's what I'm going with for now:

```
if (( $(echo "git diff --name-only --diff-filter=A HEAD" | wc -l) > 0 ))
then
  pronto_output=$(pronto run)
else
  pronto_output=$(pronto run --staged)
fi
```

**Comment by mmozuras** [comment]
@doomspork yup, looks good, sorry for taking so long 🙇 

@bjornlinder I think that [this issue](https://github.com/prontolabs/pronto/issues/263) is related to what you wrote about. Would love to read more of your thoughs on how to best approach this 😄.

**Pull request merged**
