### PR TITLE
Bitbucket deprecated its API v1.0: update all endpoints to API v2.0

### PR DESCRIPTION
**Pull request by bradrees**
Merging of 3 pull requests #347, #348 and #352, plus my changes to update the endpoints.

The only significant change here is to use the `commit` endpoint instead of the removed `changeset` endpoint. This appears to be working for me, and I'm getting the comments on my commit as per before the v2.0 change.

@doomspork, @starchow please take a look, thanks!

https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/commit/%7Bnode%7D/comments#post

### CODE REVIEW

**Comment by starchow** [comment]
thanks @bradrees, let's wait @doomspork review and merge it :D 
My pull request is not merged yet :D

**Comment by bradrees** [comment]
Actually, I'm getting duplicate comments on the commit/pr, I'll try investigate the cause. It appears to be that the existing comments are not being read or matched to the new ones.

**Comment by doomspork** [comment]
@bradrees / @starchow could you address the conflicts please? Apologizes for the delays.

**Comment by bradrees** [comment]
I've included paging to get all the comments, which addresses the duplicates issue. I've been using this for a few weeks and it appears all good now!

**Comment by bradrees** [comment]
All merged, it is good to go!

**Comment by starchow** [comment]
@doomspork could you take a look, @bradrees fixed all conflicts.

**Pull request merged**
